PrintDebugMsg         off         # on, off

ServerSoftware        yaik

ScriptDir             www/cgi-bin
LogDir                logs
PidFileDir            pid

####### UsePHP: off, php-fpm, php-cgi #######
UsePHP                php-fpm
PathPHP               127.0.0.1:9000  # [php-fpm: 127.0.0.1:9000 (/var/run/php-fpm.sock)], [php-cgi: /usr/bin/php-cgi]
#PathPHP               /usr/bin/php-cgi 

ListenBacklog         4096
TcpNoDelay            on

HeaderTableSize       0
MaxConcurrentStreams  100

MaxAcceptConnections  5005

MaxRequestsPerClient  50000

HTTP1_DataBufSize     262144    # 8192 16384 32768 262144 524288 1048576 2097152
HTTP2_RecvBufSize     16384     # 16375

MaxCgiProc            50

Timeout               200     # seconds
TimeoutKeepAlive      65      # seconds
TimeoutPoll           10      # milliseconds
TimeoutCGI            5       # seconds

ClientMaxBodySize     1000000000

fastcgi {
        ~/env  127.0.0.1:9002

        /perl/env.pl 127.0.0.1:9003
        /env.pl 127.0.0.1:9003
        
        /python/env.py 127.0.0.1:9003
        /env.py 127.0.0.1:9003
        
        /script 127.0.0.1:9003

        /upload-fcgi  127.0.0.1:9020
        /sensors      192.168.100.136:9011
}

scgi {
	~/scgi_test 127.0.0.1:9009
}

ShowMediaFiles       On

server {
	ip		0.0.0.0
	ServerPort	8080
	Redirect        https://127.0.0.1:8443
}

server {
	ip		0.0.0.0
	ServerPort	8443

	SecureConnect	on
	EnableHTTP2	on

	vhost
	{
		HostName	127.0.0.1
		DocumentRoot	www/html
		Certificate	certs/default.pem
		CertificateKey	certs/default.pem
	}
	
	vhost
	{
		HostName	my-example.com
		DocumentRoot	www/example.com
		Certificate	certs/default.pem
		CertificateKey	certs/default.pem
	}
}

server {
	ip		0.0.0.0
	ServerPort	10000

	vhost
	{
		HostName	127.0.0.1
		DocumentRoot	www/html
	}
	
	vhost
	{
		HostName	my-example.com
		DocumentRoot	www/example.com
	}
}

User                 nobody
Group                www-data
